apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: |
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVRaRldWRE1UNUtIWTJKRVoKYXdzX3Nl
    Y3JldF9hY2Nlc3Nfa2V5ID0gTFd3Rlg3OG9MdXhKd3ZPcE1jOFR4WmhLcFNhcEE3ZExxV2swTnNE
    Nwo=
